################################################################################
# Fichier de test des routes HTTP de l'API
################################################################################
@endpoint = http://localhost:{{$dotenv PORT}}

### Api-Doc
GET {{ endpoint }}/api

### Website homepage
GET {{ endpoint }}/

### page CV
GET {{ endpoint }}/cv-developpeur

### Page portfolio
GET {{ endpoint }}/portfolio

### Page contact
GET {{ endpoint }}/contact


### Page mentions legales
GET  {{ endpoint }}/mentions-legales

### Créer contact
POST {{ endpoint }}/mail
content-type: application/json

{
    "name": "polo",
    "email":"django49000@gmail.com",
    "message":"hello"
}


### 404
GET {{ endpoint }}/404vhhgfhg
